training:
  model: Glacier_HybridFlow   # GrIS_HybridFlow, Glacier_HybridFlow, AIS_HybridFlow
  epochs: 10
  batch_size: 250
  generative_scaling_constant: 0.8
  test_split_ratio: 0.2
  verbose: True
  plot_loss: True
  save_metrics: False

data:
  dir: C:/Users/Peter/Documents/Research/data/proj_MAIN_2100
  ssp: all          # all, ssp370, ssp245, ssp126, ssp119, ssp585, sspndc
  ice_source: glaciers      # gris_data, glaciers, ais
  region: 6       # Numeric for glaciers, WAIS, EAIS, PEN for AIS, None for GrIS
  ssp_as_feature: False

model:
  flow:
    num_flow_transformations: 5
    hidden_features: 128

visualizations:
  generate_plots:      # prediction_uncertainty, residuals_histogram, cross_validation_plots
    - prediction_uncertainty
    - residuals_histogram
    - cross_validation_plots
  save_plots: False

